App.js, index.js, src/.env, src/App.js, src/DB_connection.js
Hola chicos! Cree carpetas necesarias además de estructurar el back con las configuraciones necesarias:
App con midlewares
Db_connection con las conexiones necesarias para trabajar. Sobre esto hay que aclarar que para trabajarla hay que trabajar con las propias variables de entorno, pero ya esta configurado para que solo pongan su .env
Index configurado para escuchar el puerto y con sync activada para etapa de diseño.
=> Estructura del back:

.env, .gitignore, index.js, package.json, src/App.js, src/DB_connection.js, src/controllers/getFalseApiToDB.js, src/models/tblCourses.js, src/models/tblUsers.js, src/routes/CourseRouter.js, src/routes/Router.js
Se actualizan nombres de Objetos de Bases de Datos.
=> Update: Create table Users and Courses, field names reviewed

package.json, src/DB_connection.js, src/models/tblCourses.js, src/models/tblExams, src/models/tblLectures, src/models/tblQuestions
also corrected a naming error on existing courses model.
sync to the db has also been created.
=> new models created, for exams, questions and lectures.

.env, src/DB_connection.js, src/controllers/saveCoursesDB.js, src/models/tblCourses.js, src/models/tblUsers.js
updated controllers
singular name on course ID and User id
=> fixed/get courses/users :

src/controllers/getDetailsCourse.js, src/controllers/saveUsersDB.js, src/routes/CourseRouter.js
=> update/ CourseRoute get detail ID

src/routes/UsersRoutes.js
Envia data de instructores, con su PK y nombre
=> added/ instructors route

index.js, src/DB_connection.js, src/controllers/postCategoriesXCourse.js, src/controllers/postCategory.js, src/controllers/postCourse.js, src/controllers/saveCoursesDB.js, src/controllers/saveUsersDB.js, src/models/tblCategories.js, src/models/tblCourses.js, src/routes/CategoriesRouter.js, src/routes/Router.js, src/utils/falseApiCourses.js, src/utils/falseCategories.js
creada relación categorias cursos.
creada tabla de categorias
creada falsa api de categorias
funcion de agregar cursos cambiada, ya recibe un array con varias categorias creada función que agrega categorias
=> added / relación Categorias-Cursos:

src/controllers/getCategory.js, src/routes/CategoriesRouter.js, src/routes/CourseRouter.js
Atentos chicos en el front, esta ruta recibe por params el nombre del diseño y devuelve los IDs de los cursos relacionados, toca trabajarlos a través de un estado global de Courses, comparar los ids con ese estado global y renderizar con base en eso
=> added / CategoriesXUser Route.

src/controllers/getCategory.js, src/controllers/postCategory.js, src/models/tblExams.js, src/routes/CourseRouter.js, src/utils/falseApiCourses.js
Agregada ruta que trae los scores según el numero filtrado. Recordar: El filtrado manda numeros del 1 al 10 para poder mandar medias estrellitas <3
=> added / score

index.js, src/DB_connection.js, src/controllers/postCategoriesXCourse.js, src/controllers/postCourse.js, src/controllers/saveCoursesDB.js, src/controllers/saveReviewsDB.js, src/models/tblCourses.js, src/models/tblReviews.js, src/routes/CourseRouter.js, src/routes/ReviewsRouter.js, src/routes/Router.js, src/utils/falseApiReviews.js
Hola chicos, en los commit está todo más o menos claro. Ojo, hay cambios en el sistema de Score. 
Ya post course no envia scores
Ya los llamados a Courses no envian scores individuales si no array con scores por cada review. Mañana discutimos de qué forma los quieren, si quieren que tire el promedio desde atras o si ustedes promedian adelante. 
Los cambios están medio claros en los commits pero si cualquier cosa me preguntan en la mañana, nos vemos <3
=> Arreglado post course, agregado todo sobre reviews, incluido relaciones con cursos y nuevo sistema de Scores

src/DB_connection.js, src/controllers/getCategory.js, src/controllers/getScoresById.js, src/controllers/postCategoriesXCourse.js, src/controllers/postCourse.js, src/controllers/saveReviewsDB.js, src/models/tblCourses.js, src/routes/CourseRouter.js, src/routes/ReviewsRouter.js, src/utils/falseApiReviews.js
Score ahora envía un entero entre 1 y 10.
Faltan los cambios en el futuro post  reviews, agregarle esto mismo
=> fixed bug Score :

src/controllers/getCategory.js, src/controllers/getCourses.js, src/controllers/getRelatedReviews.js, src/controllers/postCourse.js, src/controllers/saveReviewsDB.js, src/routes/CourseRouter.js, src/routes/ReviewsRouter.js
Agregada la relación de reviews dentro del llamado a Courses Agregada ruta de reviews relacionados con el curso : http://localhost:3001/reviews/related/:id Recibe un ID, toca ponerle el id del curso sobre el que queremos recibir datos relacionados.
=> added/reviews :

package.json, src/App.js, src/controllers/getDetailsCourse.js, src/controllers/getRelatedReviews.js, src/controllers/postCourse.js, src/models/tblCourses.js, src/models/tblReviews.js, src/routes/CourseRouter.js, src/utils/falseApiReviews.js
Cambios necesarios para el componente Course del front
=> Cambios necesarios para el componente Course del front 

src/controllers/registerUser.js, src/models/tblReviews.js, src/models/tblUsers.js, src/utils/falseApiUsers.js
Cambios en la tabla de usuarios y la ruta. Esperemos definitiva. Ya Users recibe el usuario de auth0 por primera vez y lo guarda en la base de datos. Falta construcción de componente de cambios de perfil desde PANEL.
=> Fixed/ users routes and model :

src/controllers/postReview.js, src/models/tblReviews.js, src/routes/CourseRouter.js, src/routes/ReviewsRouter.js, src/utils/DBReal.js, src/utils/falseApiReviews.js, src/utils/falseApiUsers.js
CORREGIDA LA BASE DE DATOS CON RESPECTO AL CREATION_DATE
=> creadas nuevas rutas, para ver cursos por usuario.

src/routes/CourseRouter.js
ruta http://localhost:3001/courses/lectures/:id ya trae las lectures especificas relacionadas con el ID del curso que le manden
=> Added route lectures id

src/controllers/postReview.js, src/routes/ReviewsRouter.js
Agregada ruta que recibe el formulario de reviews y lo sube a base de datos, pendiente de debugueo
=> added: post review-

index.js, package.json, src/DB_connection.js, src/controllers/Relaciones.js, src/controllers/postCourse.js, src/controllers/saveCoursesDB.js, src/routes/CourseRouter.js, src/routes/UsersRoutes.js
[Debugueo de creacion de cursos]
=> Debugueo de creacion de cursos

src/controllers/Relaciones.js, src/controllers/postCoursexStudent.js, src/routes/CourseRouter.js, src/routes/UsersRoutes.js
A través de este link http://localhost:3001/users/user/:id se envia el id del usuario y nos traemos los cursos relacionados de él a través del array tblCourses
=> [Relacion y rutas CURSOS/USERs terminada.]

src/controllers/getScoresById.js, src/routes/ReviewsRouter.js
/reviews/avg/related/:id 
devuelve Score promediado y Scores individuales dentro de un array tblReviews
=> ruta q calcula el promedio de reviews de un curso

src/DB_connection.js, src/controllers/postCourse.js, src/controllers/postCoursexStudent.js, src/controllers/saveLectures.js, src/routes/CourseRouter.js, src/routes/UsersRoutes.js
Se cambio la función de creación de curso para que ahora también guarde la relación con los vídeos.
También se actualizó con la nueva tabla muchos a muchos cursos-users 
creación de ruta en users que relaciona lectures con users recibiendo los id de cada cual
=> Cambios necesarios acá para implementación de los videos de los cursos y creación de tablas de relación entre lectures y users 
